# This workflow runs tests using Node.js and publishes a package to GitHub Packages when a release is created.
# For more information, see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to production
        if: success()
        run: npm start
        with:
          node-version: 20  # Check compatibility with your project

      - name: Clean install dependencies
        run: npm ci

      - name: Rerun tests
        run: npm test


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Clean install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.npm_token}}
